import re

with open('src/diagram.js', 'r', encoding='utf-8') as f:
    content = f.read()

start_idx = content.find('export function renderSVG() {')
if start_idx == -1:
    print("Could not find start index")
    exit(1)

end_idx = content.find('export function toggleDiagramView() {')

new_render_svg = """export function renderSVG() {
    const container = document.getElementById('systemDiagramContainer');
    if (!container) return;

    if (!window.stateManager) return;
    const systemTree = window.stateManager.getSystemTree();
    const flatComponents = window.stateManager.getSystemComponents();

    if (!systemTree || systemTree.length === 0) {
        container.innerHTML = '<div style="padding: 20px; text-align: center; color: var(--text-muted-color);">Systemet er tomt. Diagram kan ikke genereres.</div>';
        return;
    }

    // Identify global min/max for color scaling
    let maxV = -Infinity, minV = Infinity, maxP = -Infinity, minP = Infinity, maxT = -Infinity, minT = Infinity;
    flatComponents.forEach(c => {
        const v = c.state?.velocity || 0;
        const pDrop = c.state?.pressureLoss || 0;
        const t_in = c.state?.temperature_in !== undefined ? c.state.temperature_in : 20;
        const t_out_main = c.state?.temperature_out?.outlet !== undefined ? c.state.temperature_out.outlet : t_in;

        if (!c.isAutoGenerated) {
            if (v > maxV) maxV = v;
            if (v < minV) minV = v;
            if (pDrop > maxP) maxP = pDrop;
            if (pDrop < minP) minP = pDrop;
        }

        if (t_in > maxT) maxT = t_in;
        if (t_in < minT) minT = t_in;
        if (t_out_main > maxT) maxT = t_out_main;
        if (t_out_main < minT) minT = t_out_main;
    });

    if (maxV === -Infinity) { maxV = 10; minV = 0; }
    if (maxP === -Infinity) { maxP = 2; minP = 0; }
    if (maxT === -Infinity) { maxT = 30; minT = 5; }

    let currentMin = 0;
    let currentMax = 10;
    let legendLabel = '';
    let gradientCss = '';

    if (diagramSettings.colorMode === 'velocity') {
        currentMin = minV; currentMax = maxV;
        legendLabel = 'Hastighed (m/s)';
        gradientCss = 'linear-gradient(to right, rgb(0,0,255), rgb(0,255,0), rgb(255,0,0))';
    } else if (diagramSettings.colorMode === 'pressure') {
        currentMin = minP; currentMax = maxP;
        legendLabel = 'Tryktab (Pa/m)';
        gradientCss = 'linear-gradient(to right, rgb(0,0,255), rgb(0,255,0), rgb(255,0,0))';
    } else if (diagramSettings.colorMode === 'temperature') {
        currentMin = minT; currentMax = maxT;
        legendLabel = 'Temperatur (°C)';
        gradientCss = 'linear-gradient(to right, rgb(0,0,255), rgb(0,150,255), rgb(255,255,0), rgb(255,0,0))';
    }

    if (currentMax === currentMin) currentMax = currentMin + 1;

    const formatVal = (val) => Number.isInteger(val) ? val.toString() : val.toFixed(2);

    const controlsHtml = `
    <style>
        .diagram-menu { transition: max-height 0.3s ease-out; overflow: hidden; max-height: 500px; display: flex; flex-direction: column; gap: 8px; margin-top: 5px; }
        .diagram-menu.minimized { max-height: 0px; margin-top: 0px; }
        .diagram-overlay-container { position: absolute; top: 10px; right: 10px; background: rgba(0,0,0,0.8); padding: 10px; border-radius: 8px; color: #fff; z-index: 100; min-width: 170px; box-shadow: 0 4px 6px rgba(0,0,0,0.3); font-size: 0.85rem; }
        .diagram-legend-container { position: absolute; bottom: 20px; left: 20px; background: rgba(0,0,0,0.8); padding: 10px 15px; border-radius: 8px; color: #fff; z-index: 100; min-width: 200px; box-shadow: 0 4px 6px rgba(0,0,0,0.3); font-size: 0.85rem; }
        .legend-bar { height: 12px; width: 100%; border-radius: 4px; border: 1px solid rgba(255,255,255,0.2); }
    </style>
    <div id="diagramOverlayControls" class="diagram-overlay-container">
         <div style="display:flex; justify-content:space-between; align-items:center; cursor:pointer;" onclick="document.getElementById('diagramMenuContent').classList.toggle('minimized'); this.querySelector('span').textContent = document.getElementById('diagramMenuContent').classList.contains('minimized') ? '▼' : '▲';">
            <strong style="font-size:13px;">Visning</strong>
            <span style="font-size: 10px;">▲</span>
         </div>
         <div id="diagramMenuContent" class="diagram-menu">
             <select id="diagramColorMode" class="input-field" style="width: 100%; padding: 2px; font-size: 0.85rem;" onchange="window.updateDiagramSettings()">
                <option value="default" ${diagramSettings.colorMode === 'default' ? 'selected' : ''}>Farve: Standard</option>
                <option value="velocity" ${diagramSettings.colorMode === 'velocity' ? 'selected' : ''}>Farve: Hastighed</option>
                <option value="pressure" ${diagramSettings.colorMode === 'pressure' ? 'selected' : ''}>Farve: Tryktab (Pa/m)</option>
                <option value="temperature" ${diagramSettings.colorMode === 'temperature' ? 'selected' : ''}>Farve: Temperatur (°C)</option>
             </select>
             <select id="diagramLabelMode" class="input-field" style="width: 100%; padding: 2px; font-size: 0.85rem;" onchange="window.updateDiagramSettings()">
                <option value="name" ${diagramSettings.labelMode === 'name' ? 'selected' : ''}>Tekst: Navn</option>
                <option value="detailed" ${diagramSettings.labelMode === 'detailed' ? 'selected' : ''}>Tekst: Detaljer</option>
                <option value="compact" ${diagramSettings.labelMode === 'compact' ? 'selected' : ''}>Tekst: Kompakt</option>
             </select>
             <button class="button" style="width: 100%; font-size: 0.8rem; padding: 2px;" onclick="window.resetDiagramZoom()">Zoom Alle</button>
         </div>
    </div>
    <div id="diagramLegend" class="diagram-legend-container ${diagramSettings.colorMode === 'default' ? 'hidden' : ''}">
         <strong style="font-size: 12px; display:block; margin-bottom: 8px; text-align: center;">${legendLabel}</strong>
         <div style="display: flex; align-items: center; justify-content: space-between; gap: 10px;">
             <span style="font-size: 12px; font-variant-numeric: tabular-nums;">${formatVal(currentMin)}</span>
             <div class="legend-bar" style="background: ${gradientCss}; flex-grow: 1;"></div>
             <span style="font-size: 12px; font-variant-numeric: tabular-nums;">${formatVal(currentMax)}</span>
         </div>
    </div>
    `;

    const gridStep = 80;
    let minX = 0, maxX = 0, minY = 0, maxY = 0;
    let svgContent = '';

    const updateBounds = (cx, cy) => {
        if (cx < minX) minX = cx;
        if (cx > maxX) maxX = cx;
        if (cy < minY) minY = cy;
        if (cy > maxY) maxY = cy;
    };
    
    // Start initial bounds at arbitrary 100, 60
    updateBounds(100, 60);

    const drawFlowIndicator = (cx, cy, offsetDx, offsetDy, pointDx, pointDy, flow, isTempMode = false, temp = null) => {
        const size = 8;
        const dist = 30;
        const ax = cx + offsetDx * dist;
        const ay = cy + offsetDy * dist;
        const tipX = ax + pointDx * size;
        const tipY = ay + pointDy * size;
        const backX = ax - pointDx * size;
        const backY = ay - pointDy * size;
        const pDx = -pointDy;
        const pDy = pointDx;
        const leftX = backX + pDx * size;
        const leftY = backY + pDy * size;
        const rightX = backX - pDx * size;
        const rightY = backY - pDy * size;
        const lx = ax + offsetDx * 25;
        const ly = ay + offsetDy * 25;

        let text = `${Math.round(flow)} m³/h`;
        if (isTempMode && temp !== null) {
            text = `${temp.toFixed(1)}°C | ` + text;
        }

        return `
            <polygon points="${tipX},${tipY} ${leftX},${leftY} ${rightX},${rightY}" fill="#00E5FF" />
            <text x="${lx}" y="${ly}" fill="#00E5FF" font-size="12" font-weight="bold" text-anchor="middle" dominant-baseline="middle" text-shadow="0px 0px 4px #000">${text}</text>
        `;
    };

    // Recursive drawing function
    function drawNode(comp, x, y, currentAngle, turnContext) {
        if (!comp) return;

        // Visual gray out if excluded
        const isExcluded = comp.isIncluded === false;
        const compOpacity = isExcluded ? 0.3 : 1;
        let strokeColor = getColor(comp, diagramSettings.colorMode, currentMin, currentMax);
        if (isExcluded) strokeColor = '#888888';

        const rad = currentAngle * Math.PI / 180;
        const dir = { x: Math.cos(rad), y: Math.sin(rad) };
        const perp = { x: -dir.y, y: dir.x }; // Left relative to flow

        let currentW = 12;
        const dim = comp.state?.inletDimension || comp.state?.outletDimension?.outlet || comp.state?.outletDimension?.straight;
        if (dim && dim.d) currentW = dim.d / 20;
        else if (dim && dim.w) currentW = dim.w / 20;

        const PIXELS_PER_METER = 100;
        let moveDistance = gridStep;
        let turnAngle = 0;

        let isBend = comp.type.startsWith('bend') || comp.type === 'transition_round_rect' || comp.type === 'transition_rect_round';
        if (isBend) {
            const bendAngle = comp.properties?.angle || 90;
            const turnDir = turnContext % 2 === 0 ? -1 : 1;
            turnAngle = bendAngle * turnDir;
            moveDistance = Math.max(60, currentW * 3);
        }
        else if (comp.type.includes('tee')) {
            moveDistance = Math.max(80, currentW * 4);
        }
        else if (comp.type === 'straightDuct') {
            const length_m = comp.properties?.length || 1;
            moveDistance = Math.max(40, length_m * PIXELS_PER_METER);
        }
        else {
            moveDistance = Math.max(80, currentW * 3);
        }

        let nextX = x + (dir.x * moveDistance);
        let nextY = y + (dir.y * moveDistance);

        let icon = '';
        let label = '';
        const volColor = strokeColor;
        const volOpacity = isExcluded ? "0.1" : "0.2";

        if (comp.type === 'straightDuct') {
            const w = currentW;
            const p1 = { x: x + perp.x * w, y: y + perp.y * w };
            const p2 = { x: nextX + perp.x * w, y: nextY + perp.y * w };
            const p3 = { x: nextX - perp.x * w, y: nextY - perp.y * w };
            const p4 = { x: x - perp.x * w, y: y - perp.y * w };

            let currentStrokeColor = strokeColor;
            let currentFillColor = volColor;
            let currentFillOpacity = volOpacity;

            if (diagramSettings.colorMode === 'temperature' && !isExcluded) {
                const t_in = comp.state?.temperature_in !== undefined ? comp.state.temperature_in : 20;
                const t_out = comp.state?.temperature_out?.outlet !== undefined ? comp.state.temperature_out.outlet : t_in;

                const colorStart = getColor({ state: { temperature_in: t_in } }, 'temperature', currentMin, currentMax);
                const colorEnd = getColor({ state: { temperature_in: t_out } }, 'temperature', currentMin, currentMax);

                const gradId = `grad_${comp.id}`;
                icon += `<linearGradient id="${gradId}" x1="${x}" y1="${y}" x2="${nextX}" y2="${nextY}" gradientUnits="userSpaceOnUse">
                    <stop offset="0%" stop-color="${colorStart}" />
                    <stop offset="100%" stop-color="${colorEnd}" />
                </linearGradient>`;
                currentStrokeColor = `url(#${gradId})`;
                currentFillColor = `url(#${gradId})`;
                currentFillOpacity = "0.5";
            }

            icon += `<polygon points="${p1.x},${p1.y} ${p2.x},${p2.y} ${p3.x},${p3.y} ${p4.x},${p4.y}" fill="${currentFillColor}" fill-opacity="${currentFillOpacity}" stroke="${currentStrokeColor}" stroke-width="2" />`;
            label = `Lige Kanal`;
        }
        else if (isBend) {
            const cpDistance = moveDistance * 0.5;
            const cpX = x + (dir.x * cpDistance);
            const cpY = y + (dir.y * cpDistance);

            const newRad = (currentAngle + turnAngle) * Math.PI / 180;
            const newDir = { x: Math.cos(newRad), y: Math.sin(newRad) };

            nextX = cpX + (newDir.x * cpDistance);
            nextY = cpY + (newDir.y * cpDistance);

            icon += `<path d="M${x},${y} Q${cpX},${cpY} ${nextX},${nextY}" fill="none" stroke="${volColor}" stroke-width="${currentW * 2}" stroke-opacity="${volOpacity}" stroke-linecap="butt" />`;
            icon += `<path d="M${x},${y} Q${cpX},${cpY} ${nextX},${nextY}" fill="none" stroke="${strokeColor}" stroke-width="2" />`;
            label = `Bøjning`;
        }
        else if (comp.type.includes('tee')) {
            const stubLen = moveDistance * 0.5;
            const midX = x + (dir.x * stubLen);
            const midY = y + (dir.y * stubLen);

            // Inlet piece
            icon += `<line x1="${x}" y1="${y}" x2="${midX}" y2="${midY}" stroke="${volColor}" stroke-width="${currentW * 2}" stroke-opacity="${volOpacity}" stroke-linecap="butt" />`;
            icon += `<line x1="${x}" y1="${y}" x2="${midX}" y2="${midY}" stroke="${strokeColor}" stroke-width="2" />`;

            // Straight piece
            nextX = midX + (dir.x * stubLen);
            nextY = midY + (dir.y * stubLen);
            icon += `<line x1="${midX}" y1="${midY}" x2="${nextX}" y2="${nextY}" stroke="${volColor}" stroke-width="${currentW * 2}" stroke-opacity="${volOpacity}" stroke-linecap="butt" />`;
            icon += `<line x1="${midX}" y1="${midY}" x2="${nextX}" y2="${nextY}" stroke="${strokeColor}" stroke-width="2" />`;

            // Branch piece
            const branchTurn = turnContext % 2 === 0 ? -90 : 90;
            const branchRad = (currentAngle + branchTurn) * Math.PI / 180;
            const bDx = Math.cos(branchRad);
            const bDy = Math.sin(branchRad);
            const branchX = midX + (bDx * stubLen);
            const branchY = midY + (bDy * stubLen);

            icon += `<line x1="${midX}" y1="${midY}" x2="${branchX}" y2="${branchY}" stroke="${volColor}" stroke-width="${currentW * 2}" stroke-opacity="${volOpacity}" stroke-linecap="butt" />`;
            icon += `<line x1="${midX}" y1="${midY}" x2="${branchX}" y2="${branchY}" stroke="${strokeColor}" stroke-width="2" />`;
            label = `T-stykke`;
            
            comp._branchEndX = branchX;
            comp._branchEndY = branchY;
            comp._branchAngle = currentAngle + branchTurn;
        }
        else {
            const w = currentW;
            const p1 = { x: x + perp.x * w, y: y + perp.y * w };
            const p2 = { x: nextX + perp.x * w, y: nextY + perp.y * w };
            const p3 = { x: nextX - perp.x * w, y: nextY - perp.y * w };
            const p4 = { x: x - perp.x * w, y: y - perp.y * w };
            icon += `<polygon points="${p1.x},${p1.y} ${p2.x},${p2.y} ${p3.x},${p3.y} ${p4.x},${p4.y}" fill="${volColor}" fill-opacity="${volOpacity}" stroke="${strokeColor}" stroke-width="2" />`;
            label = `${comp.name}`;
            if (comp.type === 'manualLoss') {
                const rx = x + ((nextX - x) / 2);
                const ry = y + ((nextY - y) / 2);
                icon += `<circle cx="${rx}" cy="${ry}" r="${w * 0.8}" fill="#333" stroke="${strokeColor}" stroke-width="2" />`;
            }
        }

        // Draw Labels
        let showDetails = diagramSettings.labelMode === 'detailed';
        let showCompact = diagramSettings.labelMode === 'compact';
        let labelOffset = Math.max(18, currentW + 5);
        let labelX = x + ((nextX - x) / 2) + (perp.x * labelOffset);
        let labelY = y + ((nextY - y) / 2) + (perp.y * labelOffset);
        let textAnchor = 'end';
        if (Math.abs(dir.x) > 0.5) {
            textAnchor = 'middle';
            labelY -= (currentW + 5);
        }

        let labelHtml = '';
        if (comp.properties && !comp.isAutoGenerated && !showCompact) {
            const dims = comp.state?.inletDimension;
            let dimStr = dims ? (dims.shape === 'round' ? `Ø${dims.d}` : `${dims.w}x${dims.h}`) : '';
            let vStr = comp.state?.velocity ? `${comp.state.velocity.toFixed(1)} m/s` : '';
            let dStr = isBend ? `${comp.properties.angle}°` : (comp.type === 'straightDuct' ? `${comp.properties.length}m` : '');
            
            labelHtml = `<text x="${labelX}" y="${labelY}" font-family="monospace" font-size="12" font-weight="bold" fill="#ddd" text-anchor="${textAnchor}" text-shadow="0px 0px 4px #000">${label}</text>`;
            if (showDetails) {
                 labelHtml += `<text x="${labelX}" y="${labelY + 14}" font-family="monospace" font-size="10" fill="#aaa" text-anchor="${textAnchor}" text-shadow="0px 0px 4px #000">${dimStr}  ${dStr}</text>`;
                 labelHtml += `<text x="${labelX}" y="${labelY + 26}" font-family="monospace" font-size="10" fill="#00ffff" text-anchor="${textAnchor}" text-shadow="0px 0px 4px #000">${vStr}</text>`;
                 labelHtml += `<text x="${labelX}" y="${labelY + 38}" font-family="monospace" font-size="10" fill="#ff4444" text-anchor="${textAnchor}" text-shadow="0px 0px 4px #000">${(comp.state?.pressureLoss || 0).toFixed(1)} Pa</text>`;
            }
        }

        svgContent += `<g style="opacity: ${compOpacity};">${icon}${labelHtml}</g>`;
        updateBounds(nextX, nextY);
        updateBounds(labelX, labelY);

        // --- Recurse Children ---
        let hasOpenEnds = true;
        
        if (comp.children) {
            let handledPorts = 0;
            let straightCount = 0;

            const handleChildren = (portId, sx, sy, sang) => {
                if (comp.children[portId] && comp.children[portId].length > 0) {
                    handledPorts++;
                    comp.children[portId].forEach(child => {
                        straightCount++;
                        drawNode(child, sx, sy, sang, turnContext + straightCount);
                    });
                }
            };

            // Non-Tees
            if (comp.children['outlet']) {
                handleChildren('outlet', nextX, nextY, currentAngle + turnAngle);
            }
            
            // Tees
            if (comp.type.includes('tee')) {
                // Straight
                if (comp.children['outlet_straight']) {
                     handleChildren('outlet_straight', nextX, nextY, currentAngle);
                }
                
                // Branch
                if (comp.children['outlet_branch']) {
                     handleChildren('outlet_branch', comp._branchEndX, comp._branchEndY, comp._branchAngle);
                }
            }
            
            if (handledPorts > 0) hasOpenEnds = false;
        }

        // --- Draw Arrows at Leaf nodes ---
        if (hasOpenEnds && comp.isIncluded !== false) {
            let flowOut = 0;
            let tempOut = 20;
            if (comp.state?.airflow_out) {
                flowOut = comp.state.airflow_out['outlet'] || comp.state.airflow_out['outlet_straight'] || comp.state.airflow_out['outlet_branch'] || 0;
            }
            if (comp.state?.temperature_out) {
                tempOut = comp.state.temperature_out['outlet'] || comp.state.temperature_out['outlet_straight'] || comp.state.temperature_out['outlet_branch'] || comp.state.temperature_in || 20;
            }

            if (flowOut > 0) {
                const endRad = (currentAngle + turnAngle) * Math.PI / 180;
                const endDir = { x: Math.cos(endRad), y: Math.sin(endRad) };
                const isTempMode = diagramSettings.colorMode === 'temperature';
                svgContent += drawFlowIndicator(nextX, nextY, endDir.x, endDir.y, endDir.x, endDir.y, flowOut, isTempMode, tempOut);
                updateBounds(nextX + endDir.x*50, nextY + endDir.y*50);
            }
        }
    }

    if (systemTree.length > 0) {
        let rootTemp = systemTree[0].state?.temperature_in !== undefined ? systemTree[0].state.temperature_in : 20;
        let startAirflow = systemTree[0].state?.airflow_in || 1000;
        svgContent += `
            <circle cx="100" cy="60" r="6" fill="#fff" />
            <text x="115" y="65" fill="#fff" font-size="12">Start</text>
        `;
        const startDir = { x: 0, y: 1 };
        const isTempMode = diagramSettings.colorMode === 'temperature';
        if (startAirflow) {
            svgContent += drawFlowIndicator(100, 60, -startDir.x, -startDir.y, startDir.x, startDir.y, startAirflow, isTempMode, rootTemp);
        }

        let spacingContext = 0;
        systemTree.forEach(root => {
            spacingContext++;
            drawNode(root, 100, 60, 90, spacingContext);
        });
    }

    const pad = 100;
    const viewBoxStr = `${minX - pad} ${minY - pad} ${maxX - minX + pad * 2} ${maxY - minY + pad * 2}`;

    container.innerHTML = `
        <div style="width: 100%; height: 100%; position: relative;">
            <svg id="systemSvgMap" width="100%" height="100%" viewBox="${viewBoxStr}" preserveAspectRatio="xMidYMid meet" style="background:var(--card-bg);">
               <defs>
                   <pattern id="grid" width="${gridStep}" height="${gridStep}" patternUnits="userSpaceOnUse">
                       <path d="M ${gridStep} 0 L 0 0 0 ${gridStep}" fill="none" stroke="rgba(255,255,255,0.05)" stroke-width="1"/>
                   </pattern>
               </defs>
               <rect x="${minX - pad * 2}" y="${minY - pad * 2}" width="${maxX - minX + pad * 4}" height="${maxY - minY + pad * 4}" fill="url(#grid)" />
               ${svgContent}
            </svg>
            ${controlsHtml}
        </div>
    `;

    setupDiagramInteractions();
}
"""

new_content = content[:start_idx] + new_render_svg + content[end_idx:]

with open('src/diagram.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("Rewrite of renderSVG successful")
