import re

with open('src/main.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Find the recalculateSystem function block
start_idx = content.find('// Function to recalculate the entire system chain based on Graph Topology')
if start_idx == -1:
    print("Could not find start index")
    exit(1)

end_idx = content.find('window.recalculateSystem = recalculateSystem;') + len('window.recalculateSystem = recalculateSystem;')

physics_body_start = content.find('const q_m = incomingFlow * RHO / 3600; // kg/s')
physics_body_end = content.find('        // Apply calculated state\n        component.state = newCalc;')

physics_code = content[physics_body_start:physics_body_end]
physics_code = physics_code.replace('const compAmbient = p.ambientTemp !== undefined ? p.ambientTemp : globalAmbient;', 'const compAmbient = p.ambientTemp !== undefined ? p.ambientTemp : globalParams.globalAmbient;')
physics_code = physics_code.replace('const inletDim = lastOutlet || { shape: \'round\', d: 0 };', 'const inletDim = incomingDim || { shape: \'round\', d: 0 };')
physics_code = physics_code.replace('const t_in_st = (p.path === \'straight\') ? incomingTemp : temp;', 'const t_in_st = (p.path === \'straight\') ? incomingTemp : globalParams.systemTemp;')
physics_code = physics_code.replace('const t_in_br = (p.path === \'branch\') ? incomingTemp : temp;', 'const t_in_br = (p.path === \'branch\') ? incomingTemp : globalParams.systemTemp;')
physics_code = physics_code.replace('temp;', 'globalParams.systemTemp;')


new_physics_func = f"""function calculateComponentPhysics(component, incomingFlow, incomingTemp, incomingDim, globalParams) {{
    const {{ RHO, NU, globalAmbient, systemTemp }} = globalParams;
    let newCalc = {{}};
    {physics_code}
    return newCalc;
}}

"""

new_recalculate = """// Function to recalculate the entire system chain based on Graph Topology
function recalculateSystem() {
    const graph = stateManager.getGraph();
    const userNodes = {};
    const originalEdges = [...graph.edges];

    Object.values(graph.nodes).forEach(n => {
        if (!n.isAutoGenerated) userNodes[n.id] = { ...n };
    });
    
    // Filter edges to only those connecting user nodes
    const userEdges = originalEdges.filter(e => userNodes[e.from] && userNodes[e.to]);

    // Safety check for UI elements
    const flowTypeEl = document.querySelector('input[name="systemFlowType"]:checked');
    const globalFlowType = flowTypeEl ? flowTypeEl.value : 'splitting'; // Default

    const startAirflowEl = document.getElementById('system_airflow');
    const startAirflow = startAirflowEl ? parseLocalFloat(startAirflowEl.value) : 1000;

    const tempEl = document.getElementById('temperature');
    const temp = tempEl ? parseLocalFloat(tempEl.value) : 20;

    const ambEl = document.getElementById('ambient_temperature');
    const globalAmbient = ambEl ? parseLocalFloat(ambEl.value) : 20;

    const { RHO, NU } = physics.getAirProperties(temp);
    const globalParams = { globalFlowType, globalAmbient, RHO, NU, systemTemp: temp };

    // Reset graph to rebuild with transitions
    stateManager.clearSystem();

    function traverseAndCalculate(nodeId, incomingFlow, incomingTemp, incomingDim, parentId, parentPort) {
        const comp = userNodes[nodeId];
        if (!comp) return;

        // If not included, flow is 0, but we still traverse so the subgraph exists
        const activeFlow = comp.isIncluded === false ? 0 : incomingFlow;

        // Calculate Physics
        let newCalc = calculateComponentPhysics(comp, activeFlow, incomingTemp, incomingDim, globalParams);
        comp.state = newCalc;

        let currentParentId = parentId;
        let currentParentPort = parentPort;

        // Check and Insert Transitions
        if (incomingDim && newCalc.inletDimension && !physics.areDimensionsEqual(incomingDim, newCalc.inletDimension)) {
            const transition = createTransitionComponent(incomingDim, newCalc.inletDimension, activeFlow, globalParams.globalFlowType, null);
            if (transition) {
                transition.state = calculateComponentPhysics(transition, activeFlow, incomingTemp, incomingDim, globalParams);
                stateManager.addSystemComponent(transition, currentParentId, currentParentPort, 'inlet');
                currentParentId = transition.id;
                currentParentPort = 'outlet';
            }
        }

        // Add User Component
        stateManager.addSystemComponent(comp, currentParentId, currentParentPort, 'inlet');

        // Traverse Children
        const childrenEdges = userEdges.filter(e => e.from === nodeId);
        childrenEdges.forEach(edge => {
            const outPort = edge.fromPort;
            const childId = edge.to;
            
            let portFlow = activeFlow;
            if (comp.state.airflow_out && comp.state.airflow_out[outPort] !== undefined) {
                portFlow = comp.state.airflow_out[outPort];
            } else if (comp.state.airflow_out && comp.state.airflow_out['outlet'] !== undefined) {
                portFlow = comp.state.airflow_out['outlet'];
            }

            let portTemp = incomingTemp;
            if (comp.state.temperature_out && comp.state.temperature_out[outPort] !== undefined) {
                portTemp = comp.state.temperature_out[outPort];
            } else if (comp.state.temperature_out && comp.state.temperature_out['outlet'] !== undefined) {
                portTemp = comp.state.temperature_out['outlet'];
            }

            let portDim = null;
            if (comp.state.outletDimension && comp.state.outletDimension[outPort]) {
                portDim = comp.state.outletDimension[outPort];
            } else if (comp.state.outletDimension && comp.state.outletDimension['outlet']) {
                portDim = comp.state.outletDimension['outlet'];
            }

            traverseAndCalculate(childId, portFlow, portTemp, portDim, comp.id, outPort);
        });
    }

    // Find Root Nodes
    const rootIds = Object.keys(userNodes).filter(id => !userEdges.find(e => e.to === id));
    
    // Sort root nodes just in case
    rootIds.sort((a, b) => a.localeCompare(b));

    rootIds.forEach(rootId => {
        traverseAndCalculate(rootId, startAirflow, temp, null, null, null);
    });

    ui.renderSystem();
    ui.handleComponentTypeChange();
}
window.recalculateSystem = recalculateSystem;
"""

new_content = content[:start_idx] + new_physics_func + new_recalculate + content[end_idx:]

with open('src/main.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("Rewrite successful")
